# My first cool idea is a pricing model

<<<<<<< HEAD
#### Keywords {SaaS, Pricing, B2B, Negotiations, Software Deals}
=======
#### Abstract {-}

(ref:abs1)

#### Keywords {-}
>>>>>>> d0372646eb57d9f3409fedd0d8adf79b0c083b1c

---
## To set a good price, first understand value.

The problem faced by  B2B software firms is how to gain insight into demand and use that insight to improve price achievement (a.k.a. discounting) successfully such that it improves the overall business.

Every effective modern organization uses software.  Vendors create software so they can sell it to organizations in often complex and unique deals.  Price is the point of connection between organizations and vendors, or generically between supply and demand, that enables an exchange of value.  Of the four main growth levers, pricing is the most levered.  Research by McKinsey demonstrated that a typical S&P 1500 firm can improve profit by 8% by improving price by 1%.  https://www.mckinsey.com/business-functions/marketing-and-sales/our-insights/the-power-of-pricing

Pricing well enables a firm to improve accessibility of its product for various customer segments and to maximize value capture for each segment.  Both of these increase revenue.  Now that we know we want to improve pricing, we need to explore what drives price: value.  In theory, an entity is willing to pay up to the value of the utility received from a thing for that thing.  In practice, the total cost of using software is not limited to paying the vendor, and utility received is distributed and difficult to measure in dollars.


---
## The pricing solution proposed.

The practical solution for pricing better within a B2B software business is deploying a discount management model.  In other words, to accelerate growth, B2B software firms can develop a pricing capability that enables users to understand favorable and unfavorable price ranges for each potential deal instantly or nearly so.

A discount management model requires a few standard data elements to use in segmentation include customer, market, and product.  We're looking to understand and predict willingness-to-pay for customers of a given firm, so at minimum we need historical transaction data along with segmentation elements from that firm.  To use a generic example familiar to all MIDS students as offer a quick segmentation illustration, UC Berkeley educates full-time students and part-time students (customer), caters to a local market and an international market (market), and offers undergraduate product, master product, and doctorate product (product). B2B busiensses typically retain these three types of data of a generally reliable quality in a CRM tool.  

These types of data and optionally others that that are both statistically and sensibly relevant for particular circumstances, will be blended to train a model aimed at predicting good discounts for any given deal within the scope of the model.  Since our objective function is business optimization, as opposed to model optimization, deployability is a key requirement.  A buzz-worthy neural network or random forest might optimize accuracy for a training or testing set, but a simpler tree, regression, or a combination might deliver tangible progress and also be feasibly productionalized.  These simpler algorighms also tend to yield more human insight into relationships in the data (a.k.a. business insights) than do black box models. 

Once designed, the model will be deployed into the existing sales and deal negotiation process, and may be used by sales teams, sales management, deal desks, product groups, marketing among others.  Implementation can take the form of a productized solution or a customization of existing software, eg Salesforce.  In an environment where the next best alternatives are tribal knowledge and back of the napkin math, this solution guides pricing when and where it matters to alter sales behavior.  Once deployed, many internal organizations benefit by gaining a deeper understanding of demand faced by the firm.

---
## so what?.

Pricing is important because it helps firms to maximize the utility its products generate by accessing and serving more customers, and to do a better job translating utility generated into revenue.  Secondarily, this model helps convey a common standard of demand and product value across the firm, often forcing cross-functional communication about serving customers that otherwise might not occur.  In other words, in addition to improving the top line in the short term, a well constructed pricing function forces a firm to be aligned and focused on creating customer value, which improves long term profitability.  This function can be constructed around a discount management model.

As research including the McKinsey study above indicate, the pricing lever is pressurized.  Successfully deployed successful models can substantially acceperate growth, however, successfully deployed unsuccessful models achieve failure and can harm the business.  
