# Universal Utility {#allseeingeye}

#### Keywords {universal utility, utility}


## Everyone has unique tastes

We often think we know someone, either others or ourselves, but are later surprised by a decision or action.  We think something like "that doesn't seem like him/her to do that."  Since people rarely do things that are not useful to them in some way, actions might be deduced to priortized lists of options weighted by utility.  An example to illustrate:

Everyone has a unique set of tastes and preferences for what to eat.  This set is at a granular level, for example it might include something like this: {"raw orange mini carrots":12.5, "sliglty cooked orange mini carrots":11.5,..."haricot verts sauteed in brown butter and sage":16.8...}.  We might posit that since each person has a set of tastes different than each other person, the notion of a restaurant would not seem possible to exist profitably.  However, restaurants actually exist and make money.  It seems that a limited number of offerings still satisfy a critical mass of unique tastes.  When I order at a restaurant I look at the menu and pick the one that looks most satisfactory to me based on my Priorities (healthy, not healthy, contains alergy-inducing ingredients) and priorites (seared big eye tuna: 1 billion, canned albacore tuna: 2, steamed opakapaka: 200).

Broadly speaking we all have a currnelty undefinable set of value drivers that 1) change over time and 2) seem to apply to everything.  Try to think of a thing that exists, and then try to claim you have no sense of how useful it might be to you.  (Let me know if you can!).  

## A know-it-all.

The idea is to create a universal utility model that can estimate utility of anything.  This requires tremendous amounts of data on every activity a person undertakes and a very large inference matrix.  If I have eaten Pho at Pho Basil in Boston six times, and other people who ate at Pho Basil around six times also have never been on a ducktour (Boston tour bus-boat), the model might infer that I am unlikely to have a preference for, or get utilty from, a ducktour.  If I have have a low preference for a ducktour, and other people who have a low prefernce for a ducktour also ski annually, I am likely to ski annually.  

To follow the example in class, this model will know that if I clicked 10 times on bananas and other people who clicked about 10 times on bananas also like apples, I probably like apples.

## An end.

Such a model will be useful to help align market offers to market preferences more precisely.  Such added precision may improve utility return per dollar for consumers, and may help reduce waste overall as a greater society.  If firms get better at offering higher utility offerings, then, all else equal, consumers will better off and society will waste fewer resources creating offerings that are less desireable.  If, however, firms get better at offering higher utility offerings and also know how to price to utility, then firms will be better but consumers would not greatly beneift.

As a tool, it could be used for good, for example, if open sourced and made available to everyone for free.  It could also be used as a competitive advantage by firms if it is not offered as open source.  The most likely scenario would evolve as an open source tool with premium customization, services and extensions built on top, with service providers akin to redhat.
